# Generated by Django 4.1.7 on 2023-03-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_menu_tree', '0004_menu_parent_delete_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
