# Generated by Django 4.1.7 on 2023-03-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_menu_tree', '0005_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='use_named_url',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
