# Generated by Django 4.1.7 on 2023-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_menu_tree', '0006_menu_use_named_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lolik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
