# Generated by Django 4.1.7 on 2023-03-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_menu_tree', '0007_lolik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='django_menu_tree.menu', verbose_name='Родительское меню'),
        ),
    ]
