# Generated by Django 4.1.7 on 2023-03-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_menu_tree', '0008_alter_menu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, help_text='You must not set the use_named_url flag', max_length=160, null=True, verbose_name='Custom url'),
        ),
    ]
