# Generated by Django 4.1.7 on 2023-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_menu_tree', '0009_alter_menu_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lolik',
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, help_text="If you use custom url you must not set the 'use_named_url' flag", max_length=250, null=True, verbose_name='Custom URL'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='use_named_url',
            field=models.BooleanField(default=True, help_text="Required True if you use 'named url'"),
        ),
    ]
